version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    # networks:
    #   - tyk1
    networks:
      static-network:
        ipv4_address: 172.28.128.2
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8666:8081"
    networks:
      static-network:
        ipv4_address: 172.28.128.3  
    # networks:
    #   - tyk1

# networks:
#   tyk1:
#     driver: bridge
#     config:
#     - subnet: 172.33.0.0/16

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
