version: '3'
services:
  redis:
    image: redis:latest
    networks:
      - tyk1
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8666:8081"
    networks:
      - tyk1

networks:
  tyk1:
    driver: bridge